### ISSUE TITLE
Runtime crash due to incorrect uniform buffer size

### ISSUE THREAD

**Issue by Bavitharan** [BradLarson/GPUImage3#63]
validateFunctionArguments:3485: failed assertion `Fragment Function(vignetteFragment): argument uniform[0] from buffer(1) with offset(0) and length(40) has space for 40 bytes, but argument has a length(48).'

**Comment by BradLarson** [comment]
This is due to a tricky issue that we recently uncovered with the way that we handle uniform buffers. At some point in our logic, we're allocating a buffer that is slightly too big for the size of the uniform values we are passing in.

In previous OS versions, this silently worked, even though the buffer size was wrong. In more recent OS versions, this now fails at runtime.

We're working to fix this.

**Comment by Bavitharan** [comment]
Thank you for your response. I am waiting for solution.

**Comment by wbtvc** [comment]
I has same problem，and i fixed it。This bug is in : ShaderUniformSettings.appendBufferSpace，i rewrite this function to fixed it.

**Comment by Bavitharan** [comment]
@wbtvc  Please give more details.

**Comment by artsector** [comment]
as fast fix you can increase uniformBuffer here [https://github.com/BradLarson/GPUImage3/blob/master/framework/Source/ShaderUniformSettings.swift#L194](url)

```
length: (uniformValues.count + 1) * (MemoryLayout<Float>.size),
```

but it is wrong way, i do not now how fix it correctly :)

**Comment by joshbernfeld** [comment]
Temporary fix.

Change the following in Vignette.metal from:
```swift
typedef struct {
    float2 vignetteCenter;
    float3 vignetteColor;
    float vignetteStart;
    float vignetteEnd;
} VignetteUniform;
```
to:
```swift
typedef struct {
    float vignetteStart;
    float vignetteEnd;
    float2 vignetteCenter;
    float3 vignetteColor;
} VignetteUniform;
```

**Comment by joshbernfeld** [comment]
See #91 for permanent fix
